### ISSUE TITLE
v1.7 based release

### ISSUE THREAD

**Issue by SebTM** [jirutka/swaylock-effects#19]
Hey, 

thanks for continuing sway-lock-effect 👍🏻  I wanted to ask if/when there is a plan for the next upstream merge and maybe a v1.7 based release?

Best wishes & happy Holidays :)

**Comment by WholesomeDoktor** [comment]
@SebTM have you updated sway 1.8 and tested this package? For me swaylock is giving the red screen of death.

**Comment by mnussbaum** [comment]
It looks like upstream swaylock-effects just released an update for this- https://github.com/mortie/swaylock-effects/releases/tag/v1.6-4

**Comment by jirutka** [comment]
Nope, 1.6-4 doesn’t integrate the most important change from 1.7 – the new screenlocker protocol. This fork does implement it and, since #20, it actually works (released now as 1.6.11).

**Comment by jirutka** [comment]
I’ve just released v1.7.0.0.
