### ISSUE TITLE
Add copr repository for installation on Fedora

### ISSUE THREAD

**Issue by cassis163** [jirutka/swaylock-effects#22]
I know that the old version that this fork is based on support Fedora, but that one is really old. The packaged version (1.6-1) has this really annoying bug where the `screenshots` flag returns a vertically inverted screenshot.

**Comment by jirutka** [comment]
I’m sorry, I don’t use Fedora; this initiative should come from someone who does.

**Comment by TRS-SoD** [comment]
I created a COPR build for v1.6.11 here - Forked from @eddsalkield repos: https://copr.fedorainfracloud.org/coprs/trs-sod/swaylock-effects/ 

I'm still testing it and it looks like bash autocomplete is broken at the moment. But other than that it seems to be working as expected.

I can't promise I'll maintain it perfectly. But at least there's a more recent version available.

**Comment by eddsalkield** [comment]
Thanks!
