### ISSUE TITLE
Port the red screen fix from the original repo

### ISSUE THREAD

**Issue by cab404** [jirutka/swaylock-effects#24]
Hi there!

There's a problem with newer versions of sway showing red screen on lock. 

https://github.com/mortie/swaylock-effects/releases/tag/v1.6-4

This release probably should've fixed that.

Here's a tracking issue:

https://github.com/mortie/swaylock-effects/issues/97

**Comment by cab404** [comment]
(also maaaaybe please answer mortie about maintaining this? :3 )
https://github.com/mortie/swaylock-effects/issues/92#issuecomment-1186017736

**Comment by MarijnS95** [comment]
#3 was just fixed in #20, looks like all the necessary porting and additional development work has already been done?

(Aside from some fallout where a white screen may show after DPMS on->off->on, and noticeable stutter/delay upon locking)

**Comment by cab404** [comment]
Well, I guess then the only thing left is to make a release, so we can update it's package in distros)

**Comment by bd-g** [comment]
> (also maaaaybe please answer mortie about maintaining this? :3 ) [mortie#92 (comment)](https://github.com/mortie/swaylock-effects/issues/92#issuecomment-1186017736)

@jirutka ?

**Comment by mauricekraus** [comment]
is this merged? I'm still using morties branch because this fork/new maintained version is unfortunately unusable due to this error.

**Comment by jirutka** [comment]
This was fixed in df957f1a9f6bb6176da73797ea20a788d7c0bc8e, which is available in the latest release 1.7.0.0.
