### ISSUE TITLE
[Distro Request] Add Void Linux as supported distro.

### ISSUE THREAD

**Issue by music-cat-bread** [jirutka/swaylock-effects#40]
Hello.
I have created build scripts for xbps-src (Void Linux Build Tool) and wanted to share them, because as of right now I don't see any official packages for Void.
`template` (main build script)
```
# Template file for 'swaylock-effects'
pkgname=swaylock-effects
version=1.6.11
revision=1
archs="x86_64"
build_style=meson
conf_files="/etc/pam.d/swaylock"
hostmakedepends="pkg-config wayland-devel scdoc git"
makedepends="wayland-protocols cairo-devel gdk-pixbuf-devel pam-devel libxkbcommon-devel wayland-devel libgomp-devel"
checkdepends="wayland libxkbcommon cairo"
short_desc="Swaylock, with fancy effects"
replaces=swaylock>=0
maintainer="<>"
license="MIT"
homepage="https://github.com/jirutka/swaylock-effects"
distfiles="${homepage}/archive/refs/tags/v${version}.tar.gz"
checksum=44804d1d9dff189d1b113e44b75f68eb9fc6cf76eb4638658496ad50903cb7b9
wrksrc=${pkgname}-${version}-${revision}

post_install() {
	vlicense LICENSE
}
```

NOTE: For now I have only added x86_64 architecture, because it's only architecture I can build and test on (my vm doesn't work properly with wayland so I am testing on spare laptop).
If there's anything more to do let me know. I would really like to bring your fork to Void Linux, or at least make it easier for people to install it.

**Comment by jirutka** [comment]
Please open a pull request in [void-linux/void-packages](https://github.com/void-linux/void-packages/), they will (hopefully) provide you a code review.

**Comment by Clos3y** [comment]
Sorry for necroposting, but @music-cat-bread see [this](https://github.com/void-linux/void-packages/pull/36985) and linked issues as you're not the first to attempt packaging this and its upsteam. Also see the [contributing guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md) and the [manual](https://github.com/void-linux/void-packages/blob/master/Manual.md) if you do want to try contributing.
