### ISSUE TITLE
[Feature Request]: Let the clock be permanent

### ISSUE THREAD

**Issue by Iss-in** [jirutka/swaylock-effects#42]
Currently the clock is only shown if there's some keyboard input received and disappears again after some inactivity , leaving a plain background image . 

I was wondering if it will be possible to make it permanent, adding to aesthetics and part of customization options

**Comment by jirutka** [comment]
This is weird, I see the clock all the time, I’ve never seen it disappear. About how long inactivity timeout are we talking about here?

**Comment by Iss-in** [comment]
welp, my bad 
forgot to use indicator flag
