### ISSUE TITLE
`--screenshot` makes CPU run at 100% when using more than one monitor on Hyprland

### ISSUE THREAD

**Issue by Occhioverde** [jirutka/swaylock-effects#46]
Good morning.
As per the title, running `swaylock --screenshot` on Hyprland when more than one monitor is enabled makes Swaylock hang (the lock screen is not displayed) without any error message or crash. Additionally, if `--effect-blur 7x5` is specified, the CPU usage spikes at 100%.

Output of `swaylock -d --screenshot --effect-blur 7x5`:
```
2023-08-29 15:32:05 - [main.c:1814] Found config at /home/rsacchetto/testconf
2023-08-29 15:32:05 - [main.c:1702] Config Line #1: effect-blur=7x5
2023-08-29 15:32:05 - [main.c:1702] Config Line #2: screenshot
2023-08-29 15:32:05 - [main.c:1824] Parsing CLI Args
2023-08-29 15:32:05 - [main.c:680] output name is DP-1
2023-08-29 15:32:05 - [main.c:680] output name is eDP-1
2023-08-29 15:32:05 - [main.c:641] Loaded screenshot for output DP-1
2023-08-29 15:32:05 - [main.c:641] Loaded screenshot for output DP-1
2023-08-29 15:32:05 - [main.c:641] Loaded screenshot for output eDP-1
```

**Swaylock-effects version:** 1.6.11
**Hyprland rev:** 91e28bbe9df85e2e94fbcc0137106362aea14ab5

**Comment by BLucky-gh** [comment]
Same issue here

swaylock version 1.6.11
hyprland rev 91e28bbe9df85e2e94fbcc0137106362aea14ab5

**Comment by BLucky-gh** [comment]
One more thing I noticed: the screenshot for `DP-1` (second monitor) gets loaded twice
(btw my logs are identical that's why I'm not including mine)

The issue doesn't appear when there's only a single monitor, and the logs show `2023-08-29 19:42:15 - [main.c:1911] Using ext-session-lock-v1` once the lockscreen appears

connecting the second monitor *after* the lockscreen successfully appears works, the second screen just doesn't have a screenshot, only a solid white background

**Comment by seanluse41** [comment]
+1
using home-manager and calling with the following config

`{ config, pkgs, ... }:

{
  programs.swaylock = {
    enable = true;
    package = pkgs.swaylock-effects;
    settings = {
      color = "#764783";
      daemonize = true;
      clock = true;
      ignore-empty-password = false;
      screenshots = true;
    };
  };
}
`

terminal output:

freezes on [main.c:641] Loaded screenshot for output DP-3

**Comment by jirutka** [comment]
> I love Hyprland, but this really may just be a Hyprland issue.

Yes, it most likely is. I use a multi-monitor setup on Sway and don’t have this issue. All of the recent bug reports are from Hyprland users and none of these issues are reproducible on Sway.
