### ISSUE TITLE
`pam/swaylock` installed to the wrong location (at least for Fedora)

### ISSUE THREAD

**Issue by alterNERDtive** [jirutka/swaylock-effects#48]
No idea which distributions this affects, but as there’s no general outcry about it I’m going to assume it’s not everyone.

During the install process, this happens:

```
Installing /path/to/swaylock-effects/pam/swaylock to /usr/local/etc/pam.d
```

On Fedora, this is not read by the system. The file has to be in `/etc/pam.d` (or potentially optionally in a different location, but not this one ↑). The result is swaylock not being able to check the password, and unhelpfully just stating “wrong” even for the correct password.

Copying the file to `/etc/pam.d/swaylock` solves the issue.

**Comment by alterNERDtive** [comment]
Forgot to add: see https://github.com/mortie/swaylock-effects/issues/66

**Comment by jirutka** [comment]
This depends on the `prefix` option passed to meson (see https://mesonbuild.com/Builtin-options.html). If you specify `-Dprefix=/usr`, it’s installed into `/etc/pam.d`. You can also override just the `sysconfdir`. That’s the Meson thing, it’s not specific to this project.
