### ISSUE TITLE
screenshots not working - white screen on lock

### ISSUE THREAD

**Issue by simonm** [jirutka/swaylock-effects#5]
Hi - recently the screenshot functionality seems to have stopped working. Instead of a blurred screenshot, I get a white screen (which seems to have the blur effect). It's like the screenshot part of the process is no longer functioning.  This worked without issue previously. I am not aware of exactly when it stopped working.

Env: Dell XPS 13 7390, Manjaro
```
Installed packages:
> expac -s "%-30n %v" 'sway|wl'
autotiling                     1.6-2
azote                          1.9.4-1
bemenu-wayland                 0.6.10-1
foomatic-db                    3:20220328-1
fuzzel                         1.7.0-2
grimshot                       1.6.1-1
hwloc                          2.7.1-1
sbdp                           1.0.0-1
sway-git                       r6937.1c69d0e7-1
sway-git-debug                 r6937.1c69d0e7-1
swaybg-git                     r121.69c03f6-1
swayidle                       1.7.1-3
swayimg                        1.7-1
swaylock-effects-git           r403.4b54b85-1
swaymgr                        0.1.1-1
swaync                         0.6.3-1
waybar                         0.9.13-1
wdisplays                      1.0-2
wl-clipboard                   1:2.1.0-2
wldash                         0.3.0-1
wlogout                        1.1.1-3
wlroots-git                    0.16.0.r5588.f28c0e204-1
wlroots-git-debug              0.16.0.r5588.f28c0e204-1
wofi                           1.2.4-2
xdg-desktop-portal-wlr         0.6.0-1
```

Example output:
```
❯ WAYLAND_DEBUG=1 swaylock -d --screenshots --clock --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5 --effect-vignette 0.5:0.5 --ring-color bb00cc --key-hl-color 880033 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 --grace 2 --fade-in 0.2 2> swaylock_debug.log 
```
Debug log is attached.

Please let me know if any additional information would be useful.  

Thank you
[swaylock_debug.log](https://github.com/jirutka/swaylock-effects/files/9173547/swaylock_debug.log)

**Comment by jrgiacone** [comment]
I have the same issue

**Comment by simonm** [comment]
I just changed wlroots-git, sway-git and swaybg-git to their non-git versions and the problem is resolved.

**Comment by jirutka** [comment]
Sway 1.8 hasn’t been even released yet and I haven’t tried it yet.

This Sway release will add support for the new lockscreen protocol. Swaylock already supports it and so does swaylock-effects – it came with https://github.com/mortie/swaylock-effects/pull/86 which I rebased and merged into this repository. It seems there’s some problem with this code.

Tbh, I don’t understand this code very well, so any help is welcome.
