### ISSUE TITLE
Add support for ext-session-lock-v1 

### ISSUE THREAD

**Issue by blubkatze** [jirutka/swaylock-effects#55]
Since the `wlr-input-inhibitor-unstable-v1` protocol has been [removed from wlr-protocols as deprecated](https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/merge_requests/113) in favor of [ext-session-lock-v1](https://wayland.app/protocols/ext-session-lock-v1) ([MR in wayland-protocols](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/131)).

This is also already been implemented in [swaylock](https://github.com/swaywm/swaylock/commit/1d1c75b6316d21933069a9d201f966d84099f6ca)

It does break locking in [hyprland](https://github.com/hyprwm/Hyprland/issues/3932) for example

**Comment by jirutka** [comment]
The session lock protocol is already supported. But thanks for the confirmation that Hyprland doesn’t support this protocol, it explains many issues.
