### ISSUE TITLE
Chinese localization suggestions

### ISSUE THREAD

**Issue by gfhdhytghd** [jirutka/swaylock-effects#56]
As a native Chinese speakers, I wish you could completely delete the Chinese localization of swaylock-effects. It is way better to show in English instead of such a worth Chinese.
![38A5A290-DF25-4AAC-8C0E-60BBFD27FED5](https://github.com/jirutka/swaylock-effects/assets/102898587/1045ec77-fe81-4169-baba-09d40a6e8205)

**Comment by jirutka** [comment]
Just do that, it’s already supported (https://github.com/jirutka/swaylock-effects/pull/52).

**Comment by boredland** [comment]
(or suggest proper translations!)

**Comment by jirutka** [comment]
I don’t wanna add any translations to swaylock-effects. There are only a few strings and they can be changed via CLI options and/or a configuration file – if someone wants to localise them, they can set localised strings themselves.
