### ISSUE TITLE
Poor fade-in performance since commit 4ef9fc2

### ISSUE THREAD

**Issue by MithicSpirit** [jirutka/swaylock-effects#59]
I am experiencing very poor performance with `--fade-in` starting on commit 4ef9fc280f6d3f02557a3f3b9c67006b4d002150 and continuing up to the current tip of master (determined via `git bisect`). Its parent commit 89daa147638605b2026a401088bd316abdf61f75 is fine in this regard, though fades in from a black screen instead (which I suppose is what the broken commit is trying to solve).

This poor performance corresponds to the fade-in animation being very "discrete", at around 10 FPS (while previously I'd easily get the full 60 FPS of my monitor).

**Comment by MithicSpirit** [comment]
It seems like 7c5681ce96587ce3090c6698501faeccdfdc157d (#37) is supposed to mitigate this, but it has no noticeable effect on my system.

**Comment by MithicSpirit** [comment]
Reading through the code, it seems like the issue is that the image has to be rescaled on every frame.

Performance might improve if it is scaled only once at the start, and then the scaled version is reused for each frame. That is, `render_background_image` should be split into two parts: one that actually does the scaling and simply returns a new, scaled image; and another that renders any image and assumes it to already be the correct dimensions. It is of note that changing the filter used in this function to `CAIRO_FILTER_FAST` fixes the performance issue, showing that the filter is the bottleneck, and as far as I know, the filter is only used for the scaling operation.

**Comment by jirutka** [comment]
While you’re at it, do you have any idea how to fix #25?
