### ISSUE TITLE
Desktop is momentarily shown before swaylock activates when dpms is turned back on

### ISSUE THREAD

**Issue by imoBooze** [jirutka/swaylock-effects#66]
I am running Hyprland.  I have my swayidle configuration set to first turn off the screen via 'hyprctl dispatch dpms off' and to run 'swaylock -f' a few minutes after.  I've noticed that on resume, the desktop is still shown for a split second before swaylock triggers.  The issue doesn't seem to be present when running swaylock before 'hyprctl dispatch off'.

**Comment by jirutka** [comment]
This isn’t swaylock-effects issue, it’s about your configuration.

**Comment by imoBooze** [comment]
After some testing, I was able to work around this by using the --grace option when activating swaylock _before_ the monitor turns off.  This way, there is a period of time where resuming from idle immediately unlocks, replicating the effect I was going for originally.
