### ISSUE TITLE
Feature request : don't lock on fullscreen video

### ISSUE THREAD

**Issue by yannfill** [jirutka/swaylock-effects#9]
Hi,

When I was running awesomewm I used some locker (a derivative from i3-locker that I don't remember the name) that had this feature. I don't remember if it was detecting just audio playing, video playing or fullscreen video playing to prevent locking.

**Comment by FriederHannenheim** [comment]
That's nothing that should be implemented in the screen locker. You should modify the script that starts the screen locker.

**Comment by ErikReider** [comment]
That's the idleinhibitors job, not the lock screens

**Comment by Frozzie89** [comment]
Checkout [ErikReider/SwayAudioIdleInhibit](https://github.com/ErikReider/SwayAudioIdleInhibit) to set such idle inhibitor job
